package fr.atatorus.bookservice.services;

import java.io.IOException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.xml.sax.SAXException;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-03-23T14:53:35.236+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://services.bookservice.atatorus.fr/", name = "Book")
@XmlSeeAlso({ObjectFactory.class})
public interface Book {

    @WebMethod
    @RequestWrapper(localName = "getBook", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.GetBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public fr.atatorus.bookservice.services.Book_Type getBook(
        @WebParam(name = "bookId", targetNamespace = "")
        java.lang.Long bookId
    ) throws BookNotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getBooksByTitle", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.GetBooksByTitle")
    @ResponseWrapper(localName = "getBooksByTitleResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.GetBooksByTitleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.atatorus.bookservice.services.Book_Type> getBooksByTitle(
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title
    );

    @WebMethod
    @RequestWrapper(localName = "createBook", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.CreateBook")
    @ResponseWrapper(localName = "createBookResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.CreateBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Long createBook(
        @WebParam(name = "title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "type", targetNamespace = "")
        fr.atatorus.bookservice.services.BookType type,
        @WebParam(name = "year", targetNamespace = "")
        int year,
        @WebParam(name = "authorsId", targetNamespace = "")
        java.util.List<java.lang.Long> authorsId
    );

    @WebMethod
    @RequestWrapper(localName = "getAuthorsFromBook", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.GetAuthorsFromBook")
    @ResponseWrapper(localName = "getAuthorsFromBookResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.GetAuthorsFromBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.atatorus.bookservice.services.Author> getAuthorsFromBook(
        @WebParam(name = "bookTitle", targetNamespace = "")
        java.lang.String bookTitle
    ) throws BookNotFoundException_Exception;
    
   
}
