package fr.atatorus.bookservice.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-03-23T14:53:35.253+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "BookService", 
                 // wsdlLocation = "file:/D:/sirhen_v3/repo/soap/bookclient/src/main/resources/book.wsdl",
					wsdlLocation = "file:/C:/Users/François ANDRE/workspaceNeon/bookclient/src/main/resources/book.wsdl",
                  targetNamespace = "http://services.bookservice.atatorus.fr/") 
public class BookService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.bookservice.atatorus.fr/", "BookService");
    public final static QName BookPort = new QName("http://services.bookservice.atatorus.fr/", "BookPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/François ANDRE/workspaceNeon/bookclient/src/main/resources/book.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BookService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/sirhen_v3/repo/soap/bookclient/src/main/resources/book.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BookService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BookService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BookService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BookService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Book
     */
    @WebEndpoint(name = "BookPort")
    public Book getBookPort() {
        return super.getPort(BookPort, Book.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Book
     */
    @WebEndpoint(name = "BookPort")
    public Book getBookPort(WebServiceFeature... features) {
        return super.getPort(BookPort, Book.class, features);
    }

}
