
package fr.atatorus.bookservice.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-03-23T14:53:35.222+01:00
 * Generated source version: 2.7.3
 */

@WebFault(name = "BookNotFoundException", targetNamespace = "http://services.bookservice.atatorus.fr/")
public class BookNotFoundException_Exception extends Exception {
    
    private fr.atatorus.bookservice.services.BookNotFoundException bookNotFoundException;

    public BookNotFoundException_Exception() {
        super();
    }
    
    public BookNotFoundException_Exception(String message) {
        super(message);
    }
    
    public BookNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BookNotFoundException_Exception(String message, fr.atatorus.bookservice.services.BookNotFoundException bookNotFoundException) {
        super(message);
        this.bookNotFoundException = bookNotFoundException;
    }

    public BookNotFoundException_Exception(String message, fr.atatorus.bookservice.services.BookNotFoundException bookNotFoundException, Throwable cause) {
        super(message, cause);
        this.bookNotFoundException = bookNotFoundException;
    }

    public fr.atatorus.bookservice.services.BookNotFoundException getFaultInfo() {
        return this.bookNotFoundException;
    }
}
